/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
//leetcode 389
class Solution {
public:
    char findTheDifference(string s, string t) {
        
        vector<char> str;
        vector<char> t_str;
        for(int i=0;i<s.size();i++){
            str.push_back(s[i]);
        }
        for(int i=0;i<t.size();i++){
            t_str.push_back(t[i]);
        }
        sort(str.begin(),str.end());
        sort(t_str.begin(),t_str.end());
        for(int i=0;i<s.size();i++){
            if(str[i]!=t_str[i]){
                return t_str[i];
            }
        }
        
        return t_str[t_str.size()-1];
        
    }
};